apiVersion: apps/v1
kind: Deployment

metadata:
  name: {{ include "jtl-demo.fullname" . }}
  labels:
    {{- include "jtl-demo.labels" . | nindent 4 }}

spec:
  replicas: {{ .Values.replicaCount }}

  selector:
    matchLabels:
      {{- include "jtl-demo.selectorLabels" . | nindent 6 }}

  template:
    metadata:
      labels:
        {{- include "jtl-demo.selectorLabels" . | nindent 8 }}

    spec:
      serviceAccountName: {{ include "jtl-demo.serviceAccountName" . }}

      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}

      containers:
        - name: {{ .Chart.Name }}

          securityContext:
            allowPrivilegeEscalation: false
            capabilities:
              drop:
                - ALL

          image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}

          env:
            - name: ConnectionString
              value: {{ .Values.connectionString | quote }}
          
          ports:
            - name: http
              containerPort: {{ .Values.service.targetPort }}
              protocol: TCP

          livenessProbe:
            {{- toYaml .Values.livenessProbe | nindent 12 }}

          readinessProbe:
            {{- toYaml .Values.readinessProbe | nindent 12 }}

          resources:
            {{- toYaml .Values.resources | nindent 12 }}