apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "jtl-demo.serviceAccountName" . }}
  labels:
    {{- include "jtl-demo.labels" . | nindent 4 }}
automountServiceAccountToken: {{ .Values.serviceAccount.automount }}
